### ISSUE TITLE
Ordered itemsets

### ISSUE THREAD

**Issue by lgalarra** [scikit-mine/scikit-mine#44]
Hi,

I have tested LCM's implementation successfully so far. That said, I wonder if it would be useful to have the items within itemsets naturally ordered. For example, given the following input 

``
    D1 = [[1, 2, 3], [1, 5, 2], [1, 9, 12, 2], [14, 15, 16], [14, 15, 16, 17]]
``

LCM outputs the itemset (16, 14, 15) as frequent, whereas I would have expected (14, 15, 16). I believe that having a consistent order for the output itemsets may make other tasks, such as testing, -- or discriminative pattern mining as I am doing right now -- easier. 

#### Describe your proposed solution

I have had not a look at the code that emits itemsets, but it seems that it could be a post-processing step after closure calculation and support thresholding. On the other hand, a natural ordered may not be defined for itemsets of arbitrary data types. In such cases, the notion of order could be passed as an argument (e.g., a function) to the LCM object.

Thanks for your attention,
Luis

**Comment by remiadon** [comment]
Hi Luis,
Good point !!

Short answer : Yes it's possible

----------------------

Longer answer : 

> I believe that having a consistent order for the output itemsets may make other tasks, such as testing
That's right, I already had some issue with inconsistent outputs with another algorithm using the same representation

For now itemsets are represented as python `frozenset`, mainly for 3 reasons
- a frozenset is hashable
- it's immutable
- it's a primitive data type, recognized by every Python implementation

IMO itemsets should stay hashable, it's a good practice. They also should remain immutable, to avoid opportunistic errors during the mining. The third assumption, thought, can be modified. If we import a data type from one of our dependecy, we can stick with it

My trick is to use a data type provided by pandas
```python
>>> from pandas.core.indexes.frozen import FrozenList
>>> itemset = FrozenList([2, 3])
>>> itemset[1:]  # slicing OK
FrozenList([3])
>>> hash(itemset)  # works
```

Some more simple solution might be to use the `tuple` data type
```python
>>> a = tuple((2, 3))
>>> a[1:]  # works
>>> hash(a) # also works
```

--------------
> On the other hand, a natural ordered may not be defined for itemsets of arbitrary data types

Actually we use `sortedcontainer.SortedSet` to track items in `LCM.fit`, so we already check for items to be comparable. If not, we throw an error at `.fit` time, so that `.transform` is not even called.

Hope this helps

**Comment by lgalarra** [comment]
Thanks Rémi, that helps. I would probably recommend you to include how to run an existence test in the documentation, e.g.,  
``
assert frozenset({14, 15, 16}) in patterns.itemset.values
``
It comes handy at debugging.

Cheers,
Luis

**Comment by remiadon** [comment]
fixed in https://github.com/scikit-mine/scikit-mine/commit/54a24f6ee0b95d59c32c8322334c3b6aef56cadc

doc updated see https://scikit-mine.github.io/scikit-mine/tutorials/itemsets/LCM_on_chess.html

**Comment by lgalarra** [comment]
Thanks Rémi. I still have a recommendation. I saw the tests and now you we use the tuple notation to check the existence of an itemset. Perhaps the documentation should show the "official" way to do it (if you think that such a task may be done for other reasons besides debugging).
